name: Companion
on: [push, pull_request]

jobs:
  test:
    name: Unit tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.20.1, 12.x, 14.x]
    steps:
      - name: Setup
        uses: ./.github/actions/setup
        with:
          node-version: ${{matrix.node-version}}
      - name: Run tests
        run: npm run test:companion

  deploy:
    name: Deploy
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Setup
        uses: ./.github/actions/setup
      - name: Run Companion build
        run: npm run build:companion
      - name: Deploy to heroku
        uses: akhileshns/heroku-deploy@v3.5.6
        with:
          heroku_api_key : ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: companion-demo
          heroku_email   : ${{secrets.HEROKU_USER_EMAIL}}
