name: Deploy uppy.io

on:
  push:
    branches: [master, github-actions]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2
      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: Install dependencies
        run: npm ci
      - name: Build Uppy
        run: npm run build
      - name: Build website
        run: npm run web:build
      - name: Prepare deployment
        run: npm run web:deploy --quiet
      - name: Push to Github Pages
        uses: crazy-max/ghaction-github-pages@v2
        with:
          target_branch: test-website-deploy-from-github-actions
          build_dir: /home/runner/.transloadit/uppy/deploy
          committer: 'Uppy Bot <uppybot@uppy.io>'
          author: 'Uppy Bot <uppybot@uppy.io>'
          commit_message: Update transloadit/uppy website
          fqdn: uppy.io
          jekyll: false
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
