name: Deploy uppy.io

on:
  push:
    branches: [master]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2
      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: Install dependencies
        run: npm ci
      - name: Configure git author
        run: |
          git config --global user.name 'Uppy Bot'
          git config --global user.email 'uppybot@uppy.io'
      - name: Build and deploy
        run: npm run web:deploy --quiet
