name: Deploy uppy.io

on:
  push:
    branches: [master]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Setup
        uses: ./.github/actions/setup
      - name: Configure git author
        run: |
          git config --global user.name 'Uppy Bot'
          git config --global user.email 'uppybot@uppy.io'
      - name: Build and deploy
        run: npm run web:deploy --quiet
