name: Website

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  deploy:
    name: Deploy Preview
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2
      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: Install dependencies
        run: npm ci
      - name: Build Uppy
        run: npm run build
      - name: Build website
        run: npm run web:build
      - name: Deploy to Netlify
        uses: nwtgck/actions-netlify@v1.1
        with:
          publish-dir: ./website/public
          github-token: ${{secrets.GITHUB_TOKEN}}
          deploy-message: Deploy from Github Actions
          enable-pull-request-comment: false
          enable-commit-comment: false
        env:
          NETLIFY_AUTH_TOKEN: ${{secrets.NETLIFY_AUTH_TOKEN}}
          NETLIFY_SITE_ID: ${{secrets.NETLIFY_SITE_ID}}
        # Wait for at most 1 minute for the deploy to propagate
        timeout-minutes: 1
