name: Deploy uppy.io

on:
  push:
    branches: [master, github-actions]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2
      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: Install dependencies
        run: npm ci
      - name: Build and deploy
        run: npm run web:deploy --quiet
        env:
          GHPAGES_BRANCH: test-website-deploy-from-github-actions
          GIT_AUTHOR_NAME: Uppy Bot
          GIT_COMMITTER_NAME: Uppy Bot
          GIT_AUTHOR_EMAIL: uppybot@uppy.io
          GIT_COMMITTER_EMAIL: uppybot@uppy.io
